# Generated by Django 4.0.5 on 2022-06-24 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bandeja', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='respuesta',
            old_name='descripcion',
            new_name='descripción',
        ),
        migrations.RenameField(
            model_name='ticket',
            old_name='descripcion',
            new_name='descripción',
        ),
        migrations.RenameField(
            model_name='ticket',
            old_name='titulo',
            new_name='título',
        ),
    ]
