# Generated by Django 4.0.5 on 2022-06-25 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bandeja', '0004_alter_ticket_autor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='respuesta',
            old_name='descripción',
            new_name='descripcion',
        ),
        migrations.RenameField(
            model_name='ticket',
            old_name='descripción',
            new_name='descripcion',
        ),
        migrations.RenameField(
            model_name='ticket',
            old_name='título',
            new_name='titulo',
        ),
    ]
