# Generated by Django 4.0.5 on 2022-06-28 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bandeja', '0005_rename_descripción_respuesta_descripcion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='area',
            field=models.CharField(default='Palacio', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticket',
            name='componente',
            field=models.CharField(default='Memoria RAM', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticket',
            name='pc',
            field=models.CharField(default=12, max_length=100),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Respuesta',
        ),
    ]
