# Generated by Django 4.0.5 on 2022-06-28 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bandeja', '0005_rename_descripción_respuesta_descripcion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='area',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='componente',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='pc',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='Respuesta',
        ),
    ]
