# Generated by Django 4.0.5 on 2022-06-28 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bandeja', '0006_ticket_area_ticket_componente_ticket_pc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='area',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='componente',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='pc',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
