# Generated by Django 4.0.5 on 2022-06-29 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bandeja', '0006_ticket_area_ticket_componente_ticket_pc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='area',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Área'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='descripcion',
            field=models.TextField(max_length=5000, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='pc',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='PC'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='titulo',
            field=models.CharField(max_length=100, verbose_name='Título'),
        ),
    ]
