# Generated by Django 4.0.5 on 2022-07-01 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bandeja', '0008_sugerencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='area',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Área'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='componente',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='pc',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='PC'),
        ),
    ]
