# Generated by Django 4.0.5 on 2022-06-25 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='perfil',
            old_name='image',
            new_name='imagen',
        ),
    ]
