# Generated by Django 4.0.5 on 2022-06-25 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_alter_perfil_telefono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='imagen',
            field=models.ImageField(default='fotos-perfil/default.jpg', upload_to='fotos-perfil'),
        ),
    ]
