# Generated by Django 4.0.5 on 2022-06-25 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_alter_perfil_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='legajo',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
