# Generated by Django 4.0.5 on 2022-06-28 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0008_alter_perfil_legajo'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='apellido',
            field=models.CharField(default='Apellido', max_length=150),
        ),
        migrations.AddField(
            model_name='perfil',
            name='nombre',
            field=models.CharField(default='Nombre', max_length=150),
        ),
    ]
